spring:

  application:
    name: osborne-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/osborne}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:changeme}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

jwt:
  secret: ${JWT_SECRET:261c1ec521e32e96b7cf62fa327eeae4f45e6161b5f0e2df717bc1080a53c62c}
  expiration: 900000
  refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

info:
  app:
    name: osborne-api
    version: 0.0.1-SNAPSHOT
