spring:

  application:
    name: osborne-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: 900000
  refresh-expiration: 604800000
