/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLogoutRouteImport } from './routes/_authenticated.logout'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated.goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated.budgets'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated.accounts'
import { Route as AuthenticatedGoalsNewRouteImport } from './routes/_authenticated.goals.new'
import { Route as AuthenticatedGoalsGoalIdRouteImport } from './routes/_authenticated.goals.$goalId'
import { Route as AuthenticatedBudgetsNewRouteImport } from './routes/_authenticated.budgets.new'
import { Route as AuthenticatedBudgetsBudgetIdRouteImport } from './routes/_authenticated.budgets.$budgetId'
import { Route as AuthenticatedAccountsNewRouteImport } from './routes/_authenticated.accounts.new'
import { Route as AuthenticatedAccountsAccountIdRouteImport } from './routes/_authenticated.accounts.$accountId'
import { Route as AuthenticatedGoalsGoalIdEditRouteImport } from './routes/_authenticated.goals.$goalId.edit'
import { Route as AuthenticatedBudgetsBudgetIdEditRouteImport } from './routes/_authenticated.budgets.$budgetId.edit'
import { Route as AuthenticatedAccountsAccountIdEditRouteImport } from './routes/_authenticated.accounts.$accountId.edit'
import { Route as AuthenticatedAccountsAccountIdTransactionsNewRouteImport } from './routes/_authenticated.accounts.$accountId.transactions.new'
import { Route as AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRouteImport } from './routes/_authenticated.accounts.$accountId.transactions.$transactionId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLogoutRoute = AuthenticatedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsNewRoute = AuthenticatedGoalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGoalsRoute,
} as any)
const AuthenticatedGoalsGoalIdRoute =
  AuthenticatedGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthenticatedGoalsRoute,
  } as any)
const AuthenticatedBudgetsNewRoute = AuthenticatedBudgetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBudgetsRoute,
} as any)
const AuthenticatedBudgetsBudgetIdRoute =
  AuthenticatedBudgetsBudgetIdRouteImport.update({
    id: '/$budgetId',
    path: '/$budgetId',
    getParentRoute: () => AuthenticatedBudgetsRoute,
  } as any)
const AuthenticatedAccountsNewRoute =
  AuthenticatedAccountsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const AuthenticatedAccountsAccountIdRoute =
  AuthenticatedAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const AuthenticatedGoalsGoalIdEditRoute =
  AuthenticatedGoalsGoalIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedGoalsGoalIdRoute,
  } as any)
const AuthenticatedBudgetsBudgetIdEditRoute =
  AuthenticatedBudgetsBudgetIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedBudgetsBudgetIdRoute,
  } as any)
const AuthenticatedAccountsAccountIdEditRoute =
  AuthenticatedAccountsAccountIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAccountsAccountIdRoute,
  } as any)
const AuthenticatedAccountsAccountIdTransactionsNewRoute =
  AuthenticatedAccountsAccountIdTransactionsNewRouteImport.update({
    id: '/transactions/new',
    path: '/transactions/new',
    getParentRoute: () => AuthenticatedAccountsAccountIdRoute,
  } as any)
const AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute =
  AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRouteImport.update(
    {
      id: '/transactions/$transactionId/edit',
      path: '/transactions/$transactionId/edit',
      getParentRoute: () => AuthenticatedAccountsAccountIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/budgets': typeof AuthenticatedBudgetsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/logout': typeof AuthenticatedLogoutRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/budgets/$budgetId': typeof AuthenticatedBudgetsBudgetIdRouteWithChildren
  '/budgets/new': typeof AuthenticatedBudgetsNewRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRouteWithChildren
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/accounts/$accountId/edit': typeof AuthenticatedAccountsAccountIdEditRoute
  '/budgets/$budgetId/edit': typeof AuthenticatedBudgetsBudgetIdEditRoute
  '/goals/$goalId/edit': typeof AuthenticatedGoalsGoalIdEditRoute
  '/accounts/$accountId/transactions/new': typeof AuthenticatedAccountsAccountIdTransactionsNewRoute
  '/accounts/$accountId/transactions/$transactionId/edit': typeof AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/budgets': typeof AuthenticatedBudgetsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/logout': typeof AuthenticatedLogoutRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRouteWithChildren
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/budgets/$budgetId': typeof AuthenticatedBudgetsBudgetIdRouteWithChildren
  '/budgets/new': typeof AuthenticatedBudgetsNewRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRouteWithChildren
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/accounts/$accountId/edit': typeof AuthenticatedAccountsAccountIdEditRoute
  '/budgets/$budgetId/edit': typeof AuthenticatedBudgetsBudgetIdEditRoute
  '/goals/$goalId/edit': typeof AuthenticatedGoalsGoalIdEditRoute
  '/accounts/$accountId/transactions/new': typeof AuthenticatedAccountsAccountIdTransactionsNewRoute
  '/accounts/$accountId/transactions/$transactionId/edit': typeof AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/_authenticated/logout': typeof AuthenticatedLogoutRoute
  '/_authenticated/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRouteWithChildren
  '/_authenticated/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/_authenticated/budgets/$budgetId': typeof AuthenticatedBudgetsBudgetIdRouteWithChildren
  '/_authenticated/budgets/new': typeof AuthenticatedBudgetsNewRoute
  '/_authenticated/goals/$goalId': typeof AuthenticatedGoalsGoalIdRouteWithChildren
  '/_authenticated/goals/new': typeof AuthenticatedGoalsNewRoute
  '/_authenticated/accounts/$accountId/edit': typeof AuthenticatedAccountsAccountIdEditRoute
  '/_authenticated/budgets/$budgetId/edit': typeof AuthenticatedBudgetsBudgetIdEditRoute
  '/_authenticated/goals/$goalId/edit': typeof AuthenticatedGoalsGoalIdEditRoute
  '/_authenticated/accounts/$accountId/transactions/new': typeof AuthenticatedAccountsAccountIdTransactionsNewRoute
  '/_authenticated/accounts/$accountId/transactions/$transactionId/edit': typeof AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/goals'
    | '/logout'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/budgets/$budgetId'
    | '/budgets/new'
    | '/goals/$goalId'
    | '/goals/new'
    | '/accounts/$accountId/edit'
    | '/budgets/$budgetId/edit'
    | '/goals/$goalId/edit'
    | '/accounts/$accountId/transactions/new'
    | '/accounts/$accountId/transactions/$transactionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/goals'
    | '/logout'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/budgets/$budgetId'
    | '/budgets/new'
    | '/goals/$goalId'
    | '/goals/new'
    | '/accounts/$accountId/edit'
    | '/budgets/$budgetId/edit'
    | '/goals/$goalId/edit'
    | '/accounts/$accountId/transactions/new'
    | '/accounts/$accountId/transactions/$transactionId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/accounts'
    | '/_authenticated/budgets'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/logout'
    | '/_authenticated/accounts/$accountId'
    | '/_authenticated/accounts/new'
    | '/_authenticated/budgets/$budgetId'
    | '/_authenticated/budgets/new'
    | '/_authenticated/goals/$goalId'
    | '/_authenticated/goals/new'
    | '/_authenticated/accounts/$accountId/edit'
    | '/_authenticated/budgets/$budgetId/edit'
    | '/_authenticated/goals/$goalId/edit'
    | '/_authenticated/accounts/$accountId/transactions/new'
    | '/_authenticated/accounts/$accountId/transactions/$transactionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/logout': {
      id: '/_authenticated/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthenticatedLogoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals/new': {
      id: '/_authenticated/goals/new'
      path: '/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AuthenticatedGoalsNewRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/goals/$goalId': {
      id: '/_authenticated/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/budgets/new': {
      id: '/_authenticated/budgets/new'
      path: '/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof AuthenticatedBudgetsNewRouteImport
      parentRoute: typeof AuthenticatedBudgetsRoute
    }
    '/_authenticated/budgets/$budgetId': {
      id: '/_authenticated/budgets/$budgetId'
      path: '/$budgetId'
      fullPath: '/budgets/$budgetId'
      preLoaderRoute: typeof AuthenticatedBudgetsBudgetIdRouteImport
      parentRoute: typeof AuthenticatedBudgetsRoute
    }
    '/_authenticated/accounts/new': {
      id: '/_authenticated/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AuthenticatedAccountsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/_authenticated/accounts/$accountId': {
      id: '/_authenticated/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/_authenticated/goals/$goalId/edit': {
      id: '/_authenticated/goals/$goalId/edit'
      path: '/edit'
      fullPath: '/goals/$goalId/edit'
      preLoaderRoute: typeof AuthenticatedGoalsGoalIdEditRouteImport
      parentRoute: typeof AuthenticatedGoalsGoalIdRoute
    }
    '/_authenticated/budgets/$budgetId/edit': {
      id: '/_authenticated/budgets/$budgetId/edit'
      path: '/edit'
      fullPath: '/budgets/$budgetId/edit'
      preLoaderRoute: typeof AuthenticatedBudgetsBudgetIdEditRouteImport
      parentRoute: typeof AuthenticatedBudgetsBudgetIdRoute
    }
    '/_authenticated/accounts/$accountId/edit': {
      id: '/_authenticated/accounts/$accountId/edit'
      path: '/edit'
      fullPath: '/accounts/$accountId/edit'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdEditRouteImport
      parentRoute: typeof AuthenticatedAccountsAccountIdRoute
    }
    '/_authenticated/accounts/$accountId/transactions/new': {
      id: '/_authenticated/accounts/$accountId/transactions/new'
      path: '/transactions/new'
      fullPath: '/accounts/$accountId/transactions/new'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdTransactionsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsAccountIdRoute
    }
    '/_authenticated/accounts/$accountId/transactions/$transactionId/edit': {
      id: '/_authenticated/accounts/$accountId/transactions/$transactionId/edit'
      path: '/transactions/$transactionId/edit'
      fullPath: '/accounts/$accountId/transactions/$transactionId/edit'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRouteImport
      parentRoute: typeof AuthenticatedAccountsAccountIdRoute
    }
  }
}

interface AuthenticatedAccountsAccountIdRouteChildren {
  AuthenticatedAccountsAccountIdEditRoute: typeof AuthenticatedAccountsAccountIdEditRoute
  AuthenticatedAccountsAccountIdTransactionsNewRoute: typeof AuthenticatedAccountsAccountIdTransactionsNewRoute
  AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute: typeof AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute
}

const AuthenticatedAccountsAccountIdRouteChildren: AuthenticatedAccountsAccountIdRouteChildren =
  {
    AuthenticatedAccountsAccountIdEditRoute:
      AuthenticatedAccountsAccountIdEditRoute,
    AuthenticatedAccountsAccountIdTransactionsNewRoute:
      AuthenticatedAccountsAccountIdTransactionsNewRoute,
    AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute:
      AuthenticatedAccountsAccountIdTransactionsTransactionIdEditRoute,
  }

const AuthenticatedAccountsAccountIdRouteWithChildren =
  AuthenticatedAccountsAccountIdRoute._addFileChildren(
    AuthenticatedAccountsAccountIdRouteChildren,
  )

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsAccountIdRoute: typeof AuthenticatedAccountsAccountIdRouteWithChildren
  AuthenticatedAccountsNewRoute: typeof AuthenticatedAccountsNewRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsAccountIdRoute:
    AuthenticatedAccountsAccountIdRouteWithChildren,
  AuthenticatedAccountsNewRoute: AuthenticatedAccountsNewRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedBudgetsBudgetIdRouteChildren {
  AuthenticatedBudgetsBudgetIdEditRoute: typeof AuthenticatedBudgetsBudgetIdEditRoute
}

const AuthenticatedBudgetsBudgetIdRouteChildren: AuthenticatedBudgetsBudgetIdRouteChildren =
  {
    AuthenticatedBudgetsBudgetIdEditRoute:
      AuthenticatedBudgetsBudgetIdEditRoute,
  }

const AuthenticatedBudgetsBudgetIdRouteWithChildren =
  AuthenticatedBudgetsBudgetIdRoute._addFileChildren(
    AuthenticatedBudgetsBudgetIdRouteChildren,
  )

interface AuthenticatedBudgetsRouteChildren {
  AuthenticatedBudgetsBudgetIdRoute: typeof AuthenticatedBudgetsBudgetIdRouteWithChildren
  AuthenticatedBudgetsNewRoute: typeof AuthenticatedBudgetsNewRoute
}

const AuthenticatedBudgetsRouteChildren: AuthenticatedBudgetsRouteChildren = {
  AuthenticatedBudgetsBudgetIdRoute:
    AuthenticatedBudgetsBudgetIdRouteWithChildren,
  AuthenticatedBudgetsNewRoute: AuthenticatedBudgetsNewRoute,
}

const AuthenticatedBudgetsRouteWithChildren =
  AuthenticatedBudgetsRoute._addFileChildren(AuthenticatedBudgetsRouteChildren)

interface AuthenticatedGoalsGoalIdRouteChildren {
  AuthenticatedGoalsGoalIdEditRoute: typeof AuthenticatedGoalsGoalIdEditRoute
}

const AuthenticatedGoalsGoalIdRouteChildren: AuthenticatedGoalsGoalIdRouteChildren =
  {
    AuthenticatedGoalsGoalIdEditRoute: AuthenticatedGoalsGoalIdEditRoute,
  }

const AuthenticatedGoalsGoalIdRouteWithChildren =
  AuthenticatedGoalsGoalIdRoute._addFileChildren(
    AuthenticatedGoalsGoalIdRouteChildren,
  )

interface AuthenticatedGoalsRouteChildren {
  AuthenticatedGoalsGoalIdRoute: typeof AuthenticatedGoalsGoalIdRouteWithChildren
  AuthenticatedGoalsNewRoute: typeof AuthenticatedGoalsNewRoute
}

const AuthenticatedGoalsRouteChildren: AuthenticatedGoalsRouteChildren = {
  AuthenticatedGoalsGoalIdRoute: AuthenticatedGoalsGoalIdRouteWithChildren,
  AuthenticatedGoalsNewRoute: AuthenticatedGoalsNewRoute,
}

const AuthenticatedGoalsRouteWithChildren =
  AuthenticatedGoalsRoute._addFileChildren(AuthenticatedGoalsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRouteWithChildren
  AuthenticatedLogoutRoute: typeof AuthenticatedLogoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRouteWithChildren,
  AuthenticatedLogoutRoute: AuthenticatedLogoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
